// Advisor panel: focused actions, recommendations (accept/dismiss), and
// suggested questions. The advisor is read-only — accepting a suggested
// checklist item routes through the normal item-create path (which recomputes
// readiness). AI output is labeled AI-generated and requiring human review, and
// a non-commercial-demo disclaimer is shown (Req 9, 19.3, 21).

import { useState } from 'react';
import type { AdvisorAction, Launch, Recommendation } from '../types';
import { api } from '../api';
import { ErrorState, LoadingState } from '../components/states';
import { PriorityBadge } from '../components/badges';

const ACTIONS: { key: AdvisorAction; label: string }[] = [
  { key: 'analyze', label: 'Analyze launch' },
  { key: 'find_blockers', label: 'Find blockers' },
  { key: 'suggest_checklist', label: 'Suggest checklist' },
  { key: 'review_risks', label: 'Review risks' },
  { key: 'prepare_review', label: 'Prepare review' },
  { key: 'explain_readiness', label: 'Explain readiness' },
  { key: 'reanalyze', label: 'Re-analyze' },
];

export function Advisor({ launch, onChange }: { launch: Launch; onChange: (l: Launch) => void }) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [recs, setRecs] = useState<Recommendation[] | null>(null);
  const [questions, setQuestions] = useState<string[]>([]);
  const [provider, setProvider] = useState<string>('');

  async function run(action: AdvisorAction) {
    setLoading(true);
    setError(null);
    try {
      const result = await api.analyze(launch.id, action);
      setRecs(result.analysis.recommendations);
      setQuestions(result.analysis.suggested_questions);
      setProvider(result.provider);
    } catch {
      setError('The analysis did not complete. Your launch data is unchanged.');
    } finally {
      setLoading(false);
    }
  }

  async function accept(rec: Recommendation) {
    // Only suggested checklist items are directly acceptable; accepting routes
    // through the normal create path, which recomputes readiness.
    const updated = await api.addItem(launch.id, {
      title: rec.title.replace(/^Add:?\s*/i, '') || rec.title,
      category: 'Requirements',
    });
    onChange(updated);
    dismiss(rec);
  }

  function dismiss(rec: Recommendation) {
    setRecs((cur) => (cur ? cur.filter((r) => r !== rec) : cur));
  }

  return (
    <div className="space-y-6">
      {/* Disclaimer banner (Req 21.1-21.2) */}
      <div className="rounded-md border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">
        <strong>ShipCheck Advisor</strong> produces AI-generated recommendations that require human
        review. This is a non-commercial demonstration; recommendations are not a release approval.
        The deterministic engine decides the readiness status — the advisor only explains and suggests.
      </div>

      {/* Focused actions */}
      <div className="flex flex-wrap gap-2">
        {ACTIONS.map((a) => (
          <button
            key={a.key}
            onClick={() => run(a.key)}
            disabled={loading}
            className="rounded-md border border-slate-300 px-3 py-1.5 text-sm font-medium text-slate-700 hover:bg-slate-50 disabled:opacity-50"
          >
            {a.label}
          </button>
        ))}
      </div>

      {loading && <LoadingState title="Analyzing…" />}
      {error && <ErrorState detail={error} />}

      {!loading && !error && recs !== null && (
        <>
          {provider && (
            <p className="text-xs text-slate-400">
              Generated by the “{provider}” provider · AI-generated, review before acting.
            </p>
          )}

          {recs.length === 0 ? (
            <p className="text-sm text-slate-500">No recommendations for this action.</p>
          ) : (
            <ul className="space-y-3">
              {recs.map((rec, idx) => (
                <li key={`${rec.type}-${idx}`} className="rounded-md border border-slate-200 px-4 py-3">
                  <div className="flex items-start justify-between gap-3">
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="text-sm font-medium text-slate-900">{rec.title}</span>
                        <PriorityBadge priority={rec.priority} />
                      </div>
                      <p className="mt-1 text-sm text-slate-600">{rec.reason}</p>
                      {rec.suggested_action && (
                        <p className="mt-1 text-sm text-slate-500">
                          <span className="font-medium">Suggested:</span> {rec.suggested_action}
                        </p>
                      )}
                    </div>
                    <div className="flex shrink-0 gap-2">
                      {rec.type === 'suggested_checklist_item' && (
                        <button
                          onClick={() => accept(rec)}
                          className="rounded-md bg-slate-800 px-2.5 py-1 text-xs font-medium text-white"
                        >
                          Accept
                        </button>
                      )}
                      <button
                        onClick={() => dismiss(rec)}
                        className="rounded-md border border-slate-300 px-2.5 py-1 text-xs text-slate-600"
                      >
                        Dismiss
                      </button>
                    </div>
                  </div>
                </li>
              ))}
            </ul>
          )}

          {questions.length > 0 && (
            <section>
              <h3 className="mb-2 text-sm font-semibold uppercase tracking-wide text-slate-500">
                Questions for the launch review
              </h3>
              <ul className="list-disc space-y-1 pl-5 text-sm text-slate-700">
                {questions.map((q, i) => (
                  <li key={i}>{q}</li>
                ))}
              </ul>
            </section>
          )}
        </>
      )}

      {!loading && !error && recs === null && (
        <p className="text-sm text-slate-500">Run an advisor action to see recommendations.</p>
      )}
    </div>
  );
}
