// Public read-only report: fetched by share token with no auth. Shows the
// unavailable message when the token is disabled/regenerated/unknown (Req 10).

import { useCallback, useEffect, useState } from 'react';
import type { PublicReport as Report } from '../types';
import { CATEGORIES } from '../types';
import { ApiError, api } from '../api';
import { ErrorState, LoadingState } from '../components/states';
import { SeverityBadge, StatusBadge } from '../components/badges';

export function PublicReport({ token }: { token: string }) {
  const [report, setReport] = useState<Report | null>(null);
  const [loading, setLoading] = useState(true);
  const [unavailable, setUnavailable] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    setUnavailable(false);
    try {
      setReport(await api.getPublicReport(token));
    } catch (e) {
      if (e instanceof ApiError && e.status === 404) {
        setUnavailable(true);
      } else {
        setError('Could not load the report.');
      }
    } finally {
      setLoading(false);
    }
  }, [token]);

  useEffect(() => {
    void load();
  }, [load]);

  if (loading) return <LoadingState title="Loading report…" />;
  if (unavailable) {
    return (
      <div className="py-16 text-center text-slate-500">
        <p className="text-lg font-medium text-slate-700">This report is unavailable</p>
        <p className="mt-1 text-sm">The link may have been disabled or regenerated by its owner.</p>
      </div>
    );
  }
  if (error || !report) return <ErrorState detail={error ?? 'Unknown error'} onRetry={load} />;

  const catByName = new Map(report.categories.map((c) => [c.category, c]));

  return (
    <div className="space-y-8">
      <header className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h2 className="text-2xl font-semibold text-slate-900">{report.name}</h2>
          <p className="text-sm text-slate-500">Target: {report.targetDate}</p>
        </div>
        <StatusBadge status={report.status} />
      </header>

      <p className="text-xs text-slate-400">
        Read-only launch-readiness report · last updated {report.lastUpdated}
      </p>

      <section>
        <h3 className="mb-3 text-sm font-semibold uppercase tracking-wide text-slate-500">Categories</h3>
        <div className="grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-3">
          {CATEGORIES.map((cat) => {
            const c = catByName.get(cat);
            return (
              <div key={cat} className="flex items-center justify-between rounded-md border border-slate-200 px-3 py-2">
                <span className="text-sm text-slate-700">{cat}</span>
                <span className="text-xs font-medium text-slate-500">
                  {!c || c.totalCount === 0 ? 'empty' : `${c.completeCount}/${c.totalCount}`}
                </span>
              </div>
            );
          })}
        </div>
      </section>

      {report.highPriorityRisks.length > 0 && (
        <section>
          <h3 className="mb-3 text-sm font-semibold uppercase tracking-wide text-slate-500">High-priority risks</h3>
          <ul className="space-y-2">
            {report.highPriorityRisks.map((r, i) => (
              <li key={i} className="flex items-center justify-between rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm">
                <span className="text-slate-800">{r.title}</span>
                <span className="flex items-center gap-2">
                  <SeverityBadge severity={r.severity} />
                  <span className="text-xs text-slate-500">{r.status}</span>
                </span>
              </li>
            ))}
          </ul>
        </section>
      )}

      <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
        <section>
          <h3 className="mb-2 text-sm font-semibold uppercase tracking-wide text-slate-500">
            Completed ({report.completedWork.length})
          </h3>
          <ul className="space-y-1 text-sm text-slate-700">
            {report.completedWork.map((it, i) => (
              <li key={i}>✓ {it.title}</li>
            ))}
          </ul>
        </section>
        <section>
          <h3 className="mb-2 text-sm font-semibold uppercase tracking-wide text-slate-500">
            Incomplete ({report.incompleteWork.length})
          </h3>
          <ul className="space-y-1 text-sm text-slate-700">
            {report.incompleteWork.map((it, i) => (
              <li key={i}>
                ◻ {it.title}
                {it.critical && <span className="ml-1 text-xs text-purple-600">(critical)</span>}
              </li>
            ))}
          </ul>
        </section>
      </div>

      {report.openQuestions.length > 0 && (
        <section>
          <h3 className="mb-2 text-sm font-semibold uppercase tracking-wide text-slate-500">Open questions</h3>
          <ul className="list-disc space-y-1 pl-5 text-sm text-slate-700">
            {report.openQuestions.map((q, i) => (
              <li key={i}>{q}</li>
            ))}
          </ul>
        </section>
      )}
    </div>
  );
}
